# :button_value: is the name for value	
# :value: denotes the initial value
# :responders: will be fired on the server side when the value changes
# Check http://rsence.org/server_api/file.Values.html for further info
:button_value:
  :value: 0
  :responders:
    - :method: button_responder
:text_value:
  :value: "To change this text!"
